add support for reading docconfig from pyproject.toml file
PyCQA/doc8 pull request #49
Opened 2020-09-26 13:53 UTC by swaldhoer

This pull request

- adds support for reading a doc8 configuration from a ``pyproject.toml`` file and
- removes deprecated function ``readfp`` by ``read_file``

Details:

- Reading from ini-files has not been changed, except for removing the deprecated function call to a non-deprecated one
- The ``pyproject.toml`` file is only taken into account if the toml package is available.
- If a configuration file is passed as argument and the path is not a file, it is ignored and warning is printed. No other configuration files are taken into account, therefore the default configuratoin is used.

2020-09-26 14:25 UTC, swaldhoer commented
This Pull Request is WIP, as the pyproject configurations is not parsed into the exact same object as from the ini file.

2020-10-10 11:52 UTC, ssbarnea requested changes
This will also need some testing. Also it would a good idea to covert to draft if is not ready for reviews.

2020-10-11 09:24 UTC, swaldhoer commented
> This will also need some testing. Also it would a good idea to covert to draft if is not ready for reviews.

I will add tests, that make sure, configuration dict ist the same for the current configuation files and pyproject.toml

2020-11-27 12:58 UTC, merged

2020-11-27 20:08 UTC, swaldhoer commented
erm why did this get merged? This implementation is not complaint with the current implemtation of how the ``*.doc8`` is parsed.

In my opinion the way how ``*.doc8`` is parsed is bad and it **should** be parsed the way it is done in this merge request. But this would be a breaking change. So this is something that needs to be discussed.