normalize arguments loaded from pyproject.toml (#75)
PyCQA/doc8 pull request #85
Opened 2022-04-30 18:39 UTC by ejd

This PR converts arguments loaded from a `pyproject.toml` file into the internal representation used for all other argument sources.  The `from_toml` function in `main.py` is now very similar to the existing `from_ini` function.  This conversion assumes the argument values in `pyproject.toml` take advantage of TOML types instead of using strings alone.  For example, while `doc8.ini` might have 

```
[doc8]
ignore-path = foo,bar
```

An equivalent `pyproject.toml` would have the following:

```
[tool.doc8]
ignore-path = [
    "foo",
    "bar",
]
```

2022-05-03 09:56 UTC, ssbarnea requested changes
Maybe I am missing something but my impression is that this could be done with a generic conversion from underline to dash instead of an arguably ugly chain for specific cases.

Am I missing something here, like other values that do not respect that rule? Even if I am, it would clearly make sense to create a map with replacements and loop of over it.

2022-05-03 15:12 UTC, ejd commented
I agree that the repetitive try/except blocks are ugly.  You are not missing anything -- there are no special cases where an option shouldn't be renamed.  I haven't made any contributions to this project before so I chose to base my patch on the `from_ini` function.  I'm happy to change my implementation.

2022-05-03 16:08 UTC, ejd commented
I removed the mention of `from_ini()` from my original comment because `from_toml()` no longer resembles that other function.

2022-05-04 07:41 UTC, ssbarnea approved these changes

2022-05-17 07:30 UTC, ssbarnea commented
@ejd Can you please add a test? The reason why I did not merge this fix is because I do not have any confidence that it fixes anything and that we will not break it later.

We just need a test for loading the pyproject.toml.

2022-05-17 17:38 UTC, ssbarnea commented
If anyone wants to add schema validation, we should produce an JSON Schema and use jsonschema-python project to validate it. I am already doing this on other projects but I am afraid that I do not have the time to do it here.

2022-05-17 18:09 UTC, ejd commented
Can you provide a link to one of those other projects?

2022-05-17 18:34 UTC, ssbarnea commented
https://github.com/ansible/ansible-navigator validates its own config using schema and https://github.com/ansible/ansible-lint uses schemas to validate various files.

2022-05-17 18:34 UTC, merged