Add support for tomllib
PyCQA/doc8 pull request #93
Opened 2022-07-26 09:39 UTC by JakobDev

Starting with 3.11 Python has a build-in library for parsing TOML, called `tomllib`. With this PR, tomli no longer needs to be installed when using python 3.11 to parse a pyproject.toml.

2022-07-26 13:42 UTC, ssbarnea commented
@JakobDev Can you please enable py311 testing before making this change? Take a look at https://github.com/ansible/ansible-compat/blob/main/.github/workflows/tox.yml#L119-L122 to get an idea about how to update GHA pipeline.

2022-07-26 14:04 UTC, JakobDev commented
I hope that was right

2022-07-27 11:30 UTC, ssbarnea requested changes

2022-07-27 11:30 UTC, ssbarnea commented on .github/workflows/tox.yml
Please remove this, is already implemented.

2022-07-27 11:30 UTC, ssbarnea commented on README.rst
> +* ``$CWD/pyproject.toml`` in section ``[tool.doc8]`` if ``tomli`` is installed or when using a Python version greater or equal than 3.11
Instead of causing different behavior based on presence/absense of another library, we want to keep tomli as a requirement for py<3.11.

2022-07-27 12:17 UTC, ssbarnea approved these changes

2022-07-27 12:27 UTC, merged